### ISSUE TITLE
The columns stretch out to the sides in frontend

### ISSUE THREAD

**Issue by legaspielaine** [gambitph/Stackable#1040]
1. add columns & grid block
2. set columns = 6
3. set layout = grid

then inside each column:
- add icon block
- turn on block background and set the BG color

how it looks in backend:
![image](https://user-images.githubusercontent.com/28699204/106696736-4bafe900-6618-11eb-85a2-da22cdbcfd70.png)

in frontend:
![image](https://user-images.githubusercontent.com/28699204/106696793-697d4e00-6618-11eb-82de-2bb0e7c80916.png)

Note: this happens only when using the Blocksy theme

**Comment by legaspielaine** [comment]
an issue with blocksy overwriting ugb styles

**Comment by bfintal** [comment]
I think this might not be an issue. If you have the Block Background turned on, then the block would really become really wide since the block background forces blocks to become fullwidth.

If anything, the issue may be from our Block Background since it still shows the block as fullwidth even if it's nested inside columns.

We can leave this issue alone @legaspielaine since this won't be an issue once we transfer over to v3
