### ISSUE TITLE
Issues with saving blocks using the latest Gutenberg plugin (v 5.9)

### ISSUE THREAD

**Issue by Nick-Fiasco** [gambitph/Stackable#122]
Hi,

I've experienced some issues with saving Stackable blocks with the latest version of the Gutenberg plugin. Version 5.9 which was launched today. (I have it installed in order to make use of the latest features added in the Gutenberg plugin that aren't yet in Core).

**Scenario I have been testing**
I have tried creating a Stackable Container block with just one Heading and one Paragraph block inside it. With the Gutenberg plugin installed the nested blocks do not save and therefore do not render on the frontend. You can see them in the Editor, but no nested blocks on the frontend. Just the container block itself. I have also tested with other nested core blocks like Image, same result.

If I disable the Gutenberg plugin then re-save the page it all works fine.

Are there any known bugs with the latest Gutenberg plugin? Appreciate it only publicly launched today!

**Comment by grouse9000** [comment]
Yes I was about to report something similar, when I saw this post.  I use stackable to add buttons to my website in wordpress.  I can see the buttone in the editor, but when I preview only a dot (must be the container like you said), then I go back to the editor, and cannot see the buttone or even the block anymore.  All old pages and posts are fine, it is only new editing that is not working.

**Comment by bfintal** [comment]
Hey @Nick-Fiasco and @grouse9000 

Apparently in 5.9 they [deprecated a few components which were moved to different packages](https://github.com/WordPress/gutenberg/blob/master/packages/editor/CHANGELOG.md) which resulted in undefined function errors.

The `RichText` component was affected along with other components used from the `@wordpress/editor` package. Will have to move them over to the new one while supporting the old calls.

**Comment by Nick-Fiasco** [comment]
Yeah. I did read about some more deprecations alongside the other updates and fixes they did with v5.9.

I am currently only using Stackable to test out some things before using it in live sites, so it doesn't affect me much, but might affect other users who are using it on live sites that have been updated.

Hence why I thought I should flag it up.

**Comment by bfintal** [comment]
@Nick-Fiasco Thanks for pointing it out. Contemplating the best way to handle it for things to be backward compatible for users, let me know if you have a suggestion how. I'm thinking that `wp.blockEditor.RichText` should be used if available instead of `wp.editor.RichText`. Not sure whether it's possible to do that in the [externals file](https://github.com/gambitph/Stackable/blob/master/.config/externals.js)

Since the move to wp.blockEditor was merged back in March 8 (https://github.com/WordPress/gutenberg/pull/14112), so I'm guessing around Gutenberg v5.5. Not sure what WordPress version that was out. Depending on how early that is, maybe we can just move the references to `wp.blockEditor.RichText` to easily fix the problem.

**Comment by bfintal** [comment]
@Nick-Fiasco & @grouse9000 v1.15.5 is now out with the fixes for Gutenberg 5.9 :)

**Comment by Nick-Fiasco** [comment]
Ah great! Thanks very much, that was a quick fix.
