### ISSUE TITLE
the Text Cursor of the Number 1 Label moves a step backward when typing

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#170]
**Describe the bug**
When you type the Number 1 Label, the Text Cursor moves or jumps a step backward. 

**Screenshots**
https://streamable.com/0o51j

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bfintal** [comment]
To replicate:

1. Create a number box block
2. Empty the text of the first number
3. Open the inspector, then click on the text input field for the first number
4. Type 2 different numbers
5. See that the numbers are inverted in the number area.

Initial investigation:

Might be a Gutenberg problem since RichText and TextControl are both used to change the value of the attribute and nothing more.

**Comment by yssagambit** [comment]
still not fixed

![ezgif-1-69f86c8978f9](https://user-images.githubusercontent.com/51441886/69313524-c50a2880-0c6c-11ea-9c92-f01322375850.gif)

**Comment by yssagambit** [comment]
not commonly encountered and performed.
