### ISSUE TITLE
PHP Error: Incorrect dynamic content function parameter order

### ISSUE THREAD

**Issue by vmc08** [gambitph/Stackable#2503]
![image](https://user-images.githubusercontent.com/12130528/199411219-d12894a3-f6d1-47ae-9c89-581f186de605.png)

**Comment by efc** [comment]
I am getting this same warning. I am also seeing cases where dynamic content is not being properly loaded in the editor, even though it is visible on the front end. The Stackable paragraph (text) block seems particularly vulnerable to this and sometimes appears completely blank inside query loops instead of showing its content.
