### ISSUE TITLE
Social Buttons: Little i18n issues with title and description

### ISSUE THREAD

**Issue by DAnn2012** [gambitph/Stackable#2596]
**Describe the bug**
Hi, 
I noticed two small i18n errors with the "**Social Buttons**" block.

Basically, the description that is shown in the Editor for this block is the generic "**Add a customizable button.**" and not the specific "**Add social buttons.**" which seems to be missing on translate.wordpress.org

Also, in the "**Special Blocks**" section of "**🎛 Enable & Disable Blocks**" in the _Stackable Settings_, the title that is shown is only the untranslated "**Social Buttons**". Perhaps it is because in the strings on translate.wordpress.org there is no "**Social Buttons**" string with a content "**block title**"?

Finally, in these lines referring to "**Icon Button**":

https://github.com/gambitph/Stackable/blob/be14db83480464445ccbd5223fa58545bac10632/src/block/button-group/block.json#L12-L19

the "**stk-demo**" link is to the social buttons demo and not this exact one:

https://wpstackable.com/icon-button-block/

Thanks.

**Screenshots**
**Title** issue:

![social-buttons2](https://user-images.githubusercontent.com/1197819/223201043-8481cab8-c81c-4302-b88b-0b3706cb2c09.png)

**Description** issue:

![social-buttons](https://user-images.githubusercontent.com/1197819/223201108-23e9c680-7f63-40e8-8bc7-287fe17e62cb.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Browser Version: 16.3 (17614.4.6.11.6, 17614)

**Comment by DAnn2012** [comment]
Hello @bfintal 

as soon as you can, could you take a look at this problem?

Thanks.

**Comment by bfintal** [comment]
Apologies for the very late reply here. Thanks for handling the issue with the translation @DAnn2012. 

@mxkae the only remaining issue here is to update the `stk-demo` to the correct URL.

**Comment by DAnn2012** [comment]
Hello @bfintal (and @mxkae )

But will the fix to the issue with the translation be published in the next version?

Because in the 3.8.0 version the issue is still there.

![stk1](https://github.com/gambitph/Stackable/assets/1197819/869332c7-9a02-497c-b904-8f7224c23f89)

![stk2](https://github.com/gambitph/Stackable/assets/1197819/00e784d1-ca01-4df4-a76b-a4b0d18ff07c)

Thanks.

**Comment by bfintal** [comment]
Some fixes in 41bf183430a5a8f98fc37efea27befa344a2642b (this adds the "Add social buttons" into the description)

@DAnn2012 I seem to have misunderstood this. Some have been fixed already, except for this one:

> Also, in the "Special Blocks" section of "🎛 Enable & Disable Blocks" in the Stackable Settings, the title that is shown is only the untranslated "Social Buttons". Perhaps it is because in the strings on translate.wordpress.org there is no "Social Buttons" string with a content "block title"?

If you change the website translation to Italian, "Social Buttons" text in the admin is not translated, but the translation is available. 

To reproduce:
1. Change the site language to Italian (if WP doesn't download the language pack for Stackable, go to Dashboard > Updates then update the translations on the bottom-most button on the page)
2. Go to Settings > Stacakble
3. Look for "Social Buttons" in the list of enable/disable blocks
4. See that it's not translated into Italian.

Further investigation:
- This is a bit odd since if you do in PHP `var_dump( __( "Social Buttons", STACKABLE_I18N ) );` it is translated correctly
- If you check the "Social Buttons" label in the editor, it is also translated correctly
- It is only in the admin settings where it's not translated

Stuff to take into consideration when debugging:
- To make sure JS string translations are loaded, we compile all the JS strings into `dist/translation-strings.js`
- The string "Social Buttons" was defined in `stk-variants` in `src/block/button-group/block.json` this was just recently loaded into `translation-strings.js`
- In the admin settings page, `stackable_load_js_translations` is called twice, so translation strings for the same domain are loaded twice, it can be that this is overwriting some translations (not verified)

I'm not sure why this string specifically is not being translated in the settings page only. The translation seems to be present in the language pack, or else it wouldn't have been translated in other locations.

**Comment by DAnn2012** [comment]
Hi @bfintal  and @mxkae .

With the changes made by the new 3.8.1 version and with the generation of the new .po, .mo and .json files with the latest Italian translation updates from translate.wordpress.org, the problems have been completely resolved.

Thanks again.
