### ISSUE TITLE
The Feature Grid block's image can have a blank `alt`

### ISSUE THREAD

**Issue by bfintal** [gambitph/Stackable#26]
**Describe the bug**
If there's no title in the Feature Grid block, the image won't have an `alt` attribute.

**To Reproduce**
1. Add a Feature Grid block
2. Add images, empty the titles
3. Preview the page
4. The image in the block won't have an `alt` attribute.

**Expected behavior**
The `alt` attribute from the image should be used if the title is unavailable.

The solution is to add a new `alt` attributes for the Feature Grid Block for all images, then fill it up with the `alt` of the selected image. `MediaUpload`'s `onChange` provides the `alt` meta of the image.

**Comment by a4jp-com** [comment]
This was the post I wrote from the WordPress support area.
-----------------------------------------------------------------

> I can understand that is nice but there are a few problems with those methods. The alt tag and title should be a bit different for better SEO results.
> 
> “The alt tag is used by screen readers, which are browsers used by blind and visually impaired people, to tell them what is on the image. The title attribute is shown as a tooltip when you hover over the element, so in the case of an image button, the image title could contain an extra call-to-action, like “Buy product X now for $19!”, although this is not a best practice.
> 
> Each image should have an alt text, not just for SEO purposes but also because blind and visually impaired people won’t otherwise know what the image is about, but a title attribute is not required. What’s more, most of the time it doesn’t make sense to add it. They are only available to mouse (or other pointing devices) users and the only one case where the title attribute is required for accessibility is on <iframe> and <frame> tags.” Yoast
> 
> Some image are also used on different pages with different keywords to save on loading so just getting the words from the media area wouldn’t work either in some cases.
> 
> I think it’s nice if the words are pulled from either area automatically sometimes but it is even better being able to set them properly or keep them empty if selected for some reason by users.
> 
> I’ll go to the repo if that helps for all the other messages.
> 
> Thank you so much for your reply here Benjamin.
> 
> Hope I can help make these blocks super user friendly and offer lots of useful feedback or code.

**Comment by a4jp-com** [comment]
If it is okay, I want to add these 6 extra attributes: cardLink, linkAlt, linkTitle, linkTarget, linkDownload, linkHreflang. I explain a bit why lower down. 

Which files would need to be updated to add the extra text fields and save the data?

Stackable/src/block/feature-grid/save.js and...

----------------------------------------------------------

cardLink = the URL for the whole card not just the text/button. Very useful when the link/button is not used.

linkAlt = the alt tag for both the text/button link and whole card. 
Its goal is to make images more accessible for people that can not see the screen properly or use screen readers, to make the web much more accessible per W3C accessibility guidelines. Its secondary goal, as previously mentioned by Ann Smarty on SEJ, is for people who have decided, for whatever reason, to turn off images in their web browser application. In addition, it satisfies those user agents who are also unable to “see” the images. As a rule, alternative text should include targeted keyword optimization in a context that describes what the image is about. If no alternative text exists for the image, it will be displayed as an empty image.

linkTitle = The text that pops up when the mouse is on the link.
The image title text attribute is an attribute that is used to provide additional information about the image. That being said, the image title is not used for search ranking, so it is not quite as important to optimize for. You don’t have to do anything super insane for title text optimization, however. Just use a quick, short, catchy title that complements what you optimized for the alt text, and you will be good to go.

linkTarget = What the link will be opened into. For example, a blank page (_blank, _parent, _self, _top, frame name).

linkDownload = Directs the browser to download the linked resource rather than opening it.

linkHreflang = Specifies the 2 letter language code of the linked page or resource. There might be a hyphen directly after the code with a localized area for the language. Please check a code list for examples.
For example, ja = Japan, zh-Hant = Chinese (Traditional) and zh-Hans = Chinese (Simplified).
Important note: If page X links to page Y, page Y must link back to page X. If this is not the case for all pages that use hreflang annotations, those annotations may be ignored or not interpreted correctly.

**Comment by bfintal** [comment]
@a4jp-com we'll need to limit the number of attributes for our blocks, as these can get out of hand easily.

However, we can combine some of the items to get the most use out of the other existing attributes:
- cardLink: We can just use the existing link, for some blocks (e.g. Card block), we can just make the image into a link.
- linkAlt: If the purpose of this is to make the image accessible, then I think the solution above (use the title or the card or the `alt` of the image if that's not available) would do.
- linkTitle: We can use the title of the card to fill up the `title` attribute of the link
- linkTarget: This has recently been added to Stackable :)

A few comments:
- linkHreflang: From what I understand, `hreflang` is used in the `<head>` https://moz.com/learn/seo/hreflang-tag
- linkDownload: Instead of handling force-downloaded urls in Stackable, this can be just done via another plugin like [Download Monitor](https://wordpress.org/plugins/download-monitor/) then use the download link as the block's link
