### ISSUE TITLE
[WP 6.4] Site Editor - Options menu is not showing when clicking the three dots in Navigation panel for blocks inside the Content block

### ISSUE THREAD

**Issue by andeng1106** [gambitph/Stackable#2951]
**Describe the bug**
- This issue only happens on site editor (any FSE theme)

**To Reproduce**
1. Go to Appearance > Editor
2. Make sure page is "Home"
3. Open list view
4. Add Stackable blocks in the Content block
5. Click the created block
6. Open the Navigation Panel
7. Click the three dots to open options menu
8. See that options menu doesn't open / show

**Expected behavior**
Options menu should show when clicking the three dots in Navigation panel for blocks inside the Content block.

**Screenshots**

https://github.com/gambitph/Stackable/assets/103395655/9398023b-bbaf-48f2-b020-ed868f115c07

**Comment by bfintal** [comment]
@andeng1106 this looks the same as #2934 

Here's the behavior we should end up with:
- If both list view and navigation panel are both open, the 3-dots cannot be opened - we will let this issue remain
- But if only one of them is open, the 3-dots should work (this is fixed by https://github.com/gambitph/Stackable/pull/2950)
