### ISSUE TITLE
Stackable 2: countup block always align full width

### ISSUE THREAD

**Issue by nicmare** [gambitph/Stackable#492]
<img width="600" alt="Bildschirmfoto 2019-11-26 um 13 39 09" src="https://user-images.githubusercontent.com/898582/69634276-30c80900-1052-11ea-9bcd-f155cb748a3d.png">

unset full width in alignment settings but always prints out alignfull in frontend

**Comment by bfintal** [comment]
@nicmare you might have "Block Backgrounds" turned on. 

Stackable's full-width works a little bit differently. While Block Backgrounds are turned off, the wide/full-width buttons work as what you would expect normally. But when Block Backgrounds are turned on, technically the block is always set as full-width, but then the wide/full-width buttons are now changed in order to resize only the contents of the block.

This is done so that we can achieve our concept of turning a single block into a full-width section :)

**Comment by nicmare** [comment]
ah okay now i got it. thank you ben

**Comment by bfintal** [comment]
No problem! I'll close this now 👍
