### ISSUE TITLE
Container block is adding a color (#222222) in the heading styles even when there's no color set in the container block options

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#573]
Container block is adding a color (#222222) in the heading styles even when there's no color set in the container block options

**Comment by bfintal** [comment]
Bug is described in Ticket #10790

The issue is that changing the text colors of native header and paragraph blocks don't take effect and are being overridden by `#222222`

To replicate:
1. Add a Container Block
2. Change the background of the container block to a light color (this will trigger the block to add text colors)
3. Add a Paragraph Block
4. Change the color of the text to red
5. Preview the page, the text will remain `#222222`
