### ISSUE TITLE
adding value for Container Offset, offsets the container to the left

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#705]
adding value for Container Offset offsets the container to the left

Layout: Overlap Background 4

Steps:
1. add a Feature block
2. make the layout into Overlap Background 4
3. add value for Container Offset
4. check on mobile

On mobile when you've added value for Container Offset:
![image](https://user-images.githubusercontent.com/51441886/82891721-cf411280-9f80-11ea-99f4-050d7887d64a.png)

On mobile when you've clicked reset or didn't add value for Container Offset:
![image](https://user-images.githubusercontent.com/51441886/82891711-c8b29b00-9f80-11ea-8b34-b9dd79cf1f9f.png)

**Comment by legaspielaine** [comment]
Mobile mode

When off set is = 1 or any value != 0, ✓ Expected Behavior
![when offset = 1](https://user-images.githubusercontent.com/28699204/99039310-17e99800-25c2-11eb-971f-ede2928b71d1.jpg)

When you **clicked reset or did not add any value**:
![when you reset the offset](https://user-images.githubusercontent.com/28699204/99039453-567f5280-25c2-11eb-800d-6113a5cc844a.jpg)
