### ISSUE TITLE
duplicating a page makes the blocks lose its BG and text colors

### ISSUE THREAD

**Issue by yssagambit** [gambitph/Stackable#871]
duplicating a page makes the blocks lose its BG and text colors.
this only happens on Stackable Blocks, Native Blocks retains the colors that you've set.
only happening on Version 2.11.0-global-settings-v6, not on V2.10.1
my theme is 2020

![ezgif-2-b3a36890203a](https://user-images.githubusercontent.com/51441886/92573213-07fac280-f2b8-11ea-8b16-008b9190bcd7.gif)

**Comment by blankart** [comment]
This is a plugin issue. For some reasons, the Duplicate Page plugin converts some hyphen-minus characters to utf-8 code (u002d). This only happens when declaring css variables inside the block since it does not affect classes using ```-```
e.g. var(--stk-global-color-123abc, #FFFFFF) -> var(u002du002dstk-global-color-123abc, #FFFFFF)

Using the Yoast Duplicate plugin instead solves the issue for now.
