### ISSUE TITLE
Accordion Block: Text overlaps other content

### ISSUE THREAD

**Issue by Gambit-Alyssa** [gambitph/Stackable#88]
**Describe the bug**
If you have a longer content in accordion, it will overlap other blocks.

**To Reproduce**
1. Make an accordion with longer text
2. Put any content below and save
3. View your page and expand your accordion

The accordion text will overlap on the next content.

**Expected behavior**
The accordion text shouldn't overlap the next contents.

**Comment by Gambit-Alyssa** [comment]
**Temporary Fix**
`
.ugb-accordion--open .ugb-accordion__text {
    max-height: 9000px;
}
`

**Comment by bbdf-design** [comment]
Hello,
I've had the same issue and resolved it with the fix.
But still I have the problem in my backend. If I insert the text here it overflows the container the text is in instead of expanding the container to full text height.
See attached jpg (bottom) 
![overlaping accordion in backend](https://user-images.githubusercontent.com/50144872/56968596-bee31c00-6b63-11e9-97bd-01bba9f07874.JPG)
I hope you can help.
Thanks and best regards 
(If I should open an new thread I'll do this, but I thought my problem would match with this one, so I posted it here.)

**Comment by bfintal** [comment]
Already fixed in 1.15.2
